site_name: CDS Lab
site_url: 'https://lab.library.universiteitleiden.nl/'
remote_branch: rendered
theme:
  name: material
  font: false
  favicon: 'favicon.ico'

plugins:
  - search
  - htmlproofer

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
      baselevel: 2
  - footnotes

nav:
  - 'index.md'
  - 'Projects':
    - 'projects/french-manuscripts.md'
    - 'projects/nk-posters.md'
    - 'projects/abnormal-hieratic.md'
    - 'projects/wolkers-puzzles.md'
  - 'Enriching Resources':
    - 'working-with-data/enriching-resources/index.md'
    - 'working-with-data/enriching-resources/policy-framework.md'
    - 'working-with-data/enriching-resources/policy-text.md'
    - 'working-with-data/enriching-resources/policy-images.md'
    - 'working-with-data/enriching-resources/policy-av.md'
    - 'working-with-data/enriching-resources/cookbook.md'
    - 'working-with-data/enriching-resources/enrichment.md'
  - 'Virtual Research Environments':
    - 'vre/index.md'
    - 'vre/migration.md'
  - 'purl.md'
