site_name: CDS Lab
theme:
  name: material
  font: false

plugins:
  - search
  - htmlproofer

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
      baselevel: 2
  - footnotes
