site_name: CDS Lab
theme:
  name: material
  font: false

plugins:
  - search
  - htmlproofer

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
      baselevel: 2
  - footnotes

nav:
  - 'index.md'
  - 'Projects':
    - 'projects/french-manuscripts.md'
  - 'Enriching Resources':
    - 'enriching-resources/index.md'
    - 'enriching-resources/policy-framework.md'
    - 'enriching-resources/policy-text.md'
    - 'enriching-resources/policy-images.md'
    - 'enriching-resources/policy-av.md'
    - 'enriching-resources/cookbook.md'
    - 'enriching-resources/enrichment.md'
