name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - continue-on-error: false
        name: checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run MkDocs
        run: |
          mkdocs build
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: "built-site"
          # Directory containing files to upload
          path: site
