name: Build and publish webpages
on:
  push:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - continue-on-error: false
        name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build docs
        run: mkdocs build
      - name: Deploy built docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: ${{ github.ref_name }}-html
